### ISSUE TITLE
Can't upload a level

### ISSUE THREAD

**Issue by 911TRLE** [rr-/TRCustoms#254] opened 2022-04-21 05:57 UTC
Hello,

When I try to upload a level, it downloads the file but when it's done it either start to the beginning again or the uploading just disappear like I did nothing. I tried again this morning and now it even stop before getting to 100%. 
It's confusing because there is no error message so I don't even know if it's a bug or if there's something wrong with my file ? 

Thank you

**Comment by rr-** [comment] 2022-04-21 07:41
@Klona13 to collect more information and proper reproduction steps

**Comment by Kubsy** [comment] 2022-04-21 08:14
Hey 911, I had the same problem, refreshing the page works for me as a temporary fix but you will need to refill the form again.

**Comment by 911TRLE** [comment] 2022-04-21 08:23
Hey, thank you both for your fast answers ! 

@rr- There’s no specific step. I tried both to put my file in the box and click on the box to go found it but either way the problem is the same. I tried two different browser (chrome and the microsoft one) the problem stayed the same. 

@kubsy : I tried several times at different time of the day ! Don’t know if it counts like refreashing a page but I’ll try tonight to refresh the page directly and send the file right after !
Thank you for your help !!

**Comment by rr-** [comment] 2022-04-21 09:05
At minimum I'll need:

- platform 
- browser
- browser version
- screenshots from the browser console

and circumstances under which the file "disappears by itself". Klona will help you prepare this.

**Comment by Kubsy** [comment] 2022-04-21 09:32
Ill try to reproduce it

**Comment by Kubsy** [comment] 2022-04-21 09:37
Ok I reproduced it, it was stuck at 100% for 2 minutes and this came up, even though I already put it as zip file 
![image](https://user-images.githubusercontent.com/80340234/164426597-e6ef9a00-4961-4a81-adb2-b2d88a38458d.png)
![image](https://user-images.githubusercontent.com/80340234/164426624-61a00b68-99cd-4993-bad5-89c95c9d619a.png)
![image](https://user-images.githubusercontent.com/80340234/164426650-b1126e70-ed99-4785-be19-92093492ef40.png)

**Comment by rr-** [comment] 2022-04-21 09:40
This is a different problem than the OP is experiencing.

**Comment by 911TRLE** [comment] 2022-04-21 10:20
Oh yes it must be different than Kubsy issue because I never had this red message ! 
I’ll try to get the informations you want but I am not very good at this kind of stuff I’ll do my best ! 
what do you mean by « plateform » ? 
and by « browser console » you mean the kind of stuff Kubsy posted ? 

Thank you both !

**Comment by Klona13** [comment] 2022-04-21 19:50
Could you please share this file in question so we can test it? @911TRLE

**Comment by 911TRLE** [comment] 2022-04-21 19:53
Hello,
So I tried to found what @rr- asked for, so there is a screenshot of the screen with a box containing informations about "upload fails" I hope it's the right thing you needed. Also my browser is : Chrome Version 100.0.4896.127 (Build officiel) (64 bits)
And for @Klona13 here is my level file : https://we.tl/t-08TuBmarhP
Here's the screenshot I was talking about:
![SCREENTRCUSTOMSUPLOADFAIL](https://user-images.githubusercontent.com/104123860/164541815-9fedbe32-d46a-44c9-9d40-2da88817be46.jpg)
 Thank you very much for your help !

**Comment by Klona13** [comment] 2022-04-21 20:19
@911TRLE one more thing
Can you try to get this error again and check the Network tab? To show the information for where the upload error occured please.

**Comment by 911TRLE** [comment] 2022-04-21 20:52
It's good to know that you were able to upload the file, it means that at least nothing is wrong with the file itself ! :)

Here's the screenshot of the network tab after it failed to upload. This time there is so red error message... 
![SCREENTRCUSTOMSUPLOADFAIL2](https://user-images.githubusercontent.com/104123860/164550101-a4533aa3-af94-4623-a28c-fa0921b82998.jpg)

as you can see with the "level file" upload box on the website, it appears like nothing happened at all after the error

**Comment by 911TRLE** [comment] 2022-04-21 20:56
Here is another screen with the rest of the info in the right window : 
![SCREENTRCUSTOMSUPLOADFAIL2](https://user-images.githubusercontent.com/104123860/164550832-dc16f63a-ef75-445c-bad8-688b9764b60c.jpg)

**Comment by Klona13** [comment] 2022-04-21 20:57
Could you please expand the inspector? :)

**Comment by 911TRLE** [comment] 2022-04-21 21:01
Yes :)
I click on the red "upload" line it shows this : 
![SCREENTRCUSTOMSUPLOADFAIL2](https://user-images.githubusercontent.com/104123860/164551385-885caf3d-b74e-4267-a46e-27e3f408d88d.jpg)

And I think this is the inspector but not sure : 
![SCREENTRCUSTOMSUPLOADFAIL4](https://user-images.githubusercontent.com/104123860/164551537-5c87e42d-7879-4cbf-a8ab-0e2692edfb2f.jpg)
![SCREENTRCUSTOMSUPLOADFAIL3](https://user-images.githubusercontent.com/104123860/164551560-242fe120-a109-4227-aa58-a744a88a703d.jpg)

**Comment by Klona13** [comment] 2022-04-21 21:06
I meant that you can resize the inspector window to reveal more info.

**Comment by 911TRLE** [comment] 2022-04-21 21:19
Oh ! Ok ! Sorry !!
here it is:
![SCREENTRCUSTOMSUPLOADFAIL9](https://user-images.githubusercontent.com/104123860/164553868-14bef9b3-b2cb-45f5-a21f-274b4497fe55.jpg)
![SCREENTRCUSTOMSUPLOADFAIL10](https://user-images.githubusercontent.com/104123860/164553890-ab7ae0f1-bb57-4fc2-a3f3-73b54a88f020.jpg)
![SCREENTRCUSTOMSUPLOADFAIL11](https://user-images.githubusercontent.com/104123860/164553913-6bdd8239-d49d-4f8d-9833-0762547fda13.jpg)
![SCREENTRCUSTOMSUPLOADFAIL5](https://user-images.githubusercontent.com/104123860/164553933-38ffe4eb-fcb9-4733-9734-0fdd905ac5b0.jpg)
![SCREENTRCUSTOMSUPLOADFAIL6](https://user-images.githubusercontent.com/104123860/164553952-d52c7060-d64e-44d5-890f-26f8b8b362b1.jpg)
![SCREENTRCUSTOMSUPLOADFAIL7](https://user-images.githubusercontent.com/104123860/164553980-019437b8-2e03-4fb8-a997-7202fdedf867.jpg)
![SCREENTRCUSTOMSUPLOADFAIL8](https://user-images.githubusercontent.com/104123860/164553992-d00b4a4d-27c2-41b7-95cc-3d2d82739cec.jpg)

**Comment by Klona13** [comment] 2022-04-21 22:12
@rr- Please let me know if this is useful or if more is needed?

**Comment by rr-** [comment] 2022-04-21 22:16
So what's the error?

"The submitted data was not a file", "the file is not a zip", or upload randomly resetting?

**Comment by Klona13** [comment] 2022-04-22 00:29
I think the upload simply fails after it reaches 100% as there is never a response after it's completed other than that red message

**Comment by Klona13** [comment] 2022-04-22 12:18
@911TRLE Could you try to upload a tiny zipped file instead?

**Comment by 911TRLE** [comment] 2022-04-22 18:56
Hello,

So I have tried to upload a very small zipped file and the upload worked ! So I think maybe my file is too big ? 
I tried to reduce as much as I could the size of my file (from 150Mo to 80Mo) and I tried to upload it. It failed again just like the first one... :(

**Comment by 911TRLE** [comment] 2022-04-23 15:18
Hello,
I am at my mom’s house this week-end  and she lets me use her computer to try to upload the file and it worked !! I am so happy it worked on her computer ! :) now I just need to wait for it to be approved by the staff ! :)
problem is still there on my computer but at the very least I have this solution ! 
please let me know if you ever found out what’s wrong with mine ! 
Again, thank you for your help and patience and hard work on this website !

**Comment by Kubsy** [comment] 2022-04-23 16:38
Terrific :)

**Comment by rr-** [comment] 2022-04-23 21:18
Sadly I can't reproduce it no matter how I try…

The logs indicate that the connection was really unstable. As such I suppose we could introduce resumable file uploads at some point.

Since the OP has managed to find a way to upload the level over a more stable connection, I suppose we could close this ticket and add a backend item for resumable file uploads. @Klona13 thoughts?

**Comment by Klona13** [comment] 2022-04-23 21:39
Before proceeding with thoughts, I would like to ask @911TRLE first:
Can I know how you zipped this file and what you used?

**Comment by 911TRLE** [comment] 2022-04-24 06:38
@rr- oh it’s interesting to know that it would have something to do with the internet connexion !! 

@Klona13 : I used winrar to zip the file ;) 

thanks again to both of you !!

**Closed** 2022-04-24 12:07 UTC
