### ISSUE TITLE
Text alignment in reviews

### ISSUE THREAD

**Issue by MatieTR** [rr-/TRCustoms#230] opened 2022-04-08 20:32 UTC
Alignment seems to have changed in reviews, some fill out the entire box, some have `<br> `added everywhere within the text, breaking it up completely. Example of good vs bad alignment:

![image](https://user-images.githubusercontent.com/48183219/162525650-fce876b5-b272-4bbe-a849-26db8f7ce3ca.png)

**Comment by rr-** [comment] 2022-04-08 21:01
Duplicate of #220

**Closed by rr-** 2022-04-08 21:01 UTC
