### ISSUE TITLE
Profile - Inaccurate number of released levels 

### ISSUE THREAD

**Issue by Iodum99** [rr-/TRCustoms#185] opened 2022-03-28 22:16 UTC
Some authors seem to have wrong number of levels released displayed on their profile probably due to uploading and removing test levels (eg. Raider99, Klona)

**Comment by rr-** [comment] 2022-03-28 23:07
This number is almost certainly right, but it includes rejected levels.  @Klona13 ?

**Comment by Klona13** [comment] 2022-03-29 03:26
Yep. Correct. 
@Iodum99 it was this unapproved level increasing the count. can you see in on the "My levels" Button list on your profile?
https://trcustoms.org/levels/3373

**Comment by Klona13** [comment] 2022-03-29 08:35
I agree cause it would look weird if someone visits a profile and only sees 3 levels listed but the author submits 2 drafts that are going back and forth with mods for edits.

**Comment by Klona13** [comment] 2022-03-30 19:39
Now it's showing 0 for levels and reviews despite there being some. 

![image](https://user-images.githubusercontent.com/93257509/160917071-5450a97e-97e2-4cc9-8587-e2ddb9b8d2db.png)

**Comment by rr-** [comment] 2022-03-30 19:45
I changed the mechanism to store the counts in the user and forgot to recalculate the numbers. Fixed. Can you test if the numbers change in reaction to level and review deletion/upload etc.?

**Comment by Klona13** [comment] 2022-03-30 19:54
It works for adding levels, adding reviews, and removing reviews.

The only issue now is that it doesn't decrease if a level is deleted.

**Comment by rr-** [comment] 2022-03-30 20:22
Sadly I cannot reproduce this, is it happening with the authored level count or reviewed level count for you?

**Comment by Klona13** [comment] 2022-03-31 21:49
> Sadly I cannot reproduce this, is it happening with the authored level count or reviewed level count for you?

It happens to levels that have been approved. The count is even stuck if the level gets an author transfership.

I created a level with Klona and Raider99 as author and approved them so the count increases:
Me:
![image](https://user-images.githubusercontent.com/93257509/161154966-d18a3da2-50a8-4918-bdcd-f496173d7f66.png)
Raider99:
![image](https://user-images.githubusercontent.com/93257509/161154871-6c06b10d-55a5-4607-ab76-157813460254.png)

I deleted the level and these counts STAYED.

I created a level as super.

The count didn't increase after I changed author to Klona:
![image](https://user-images.githubusercontent.com/93257509/161154123-12ea7081-3f80-4cff-8752-b89f1ba6b3ed.png)

If you see here, super has no levels but the count is at 1:
https://trcustoms.org/users/1

**Comment by Klona13** [comment] 2022-04-09 00:01
The count won't increase for listed authors when the level is just created/approved/edited.

It only increases if I...
Remove all authors in the edit form by assigning it to some other user(s) and then add them back in and click on update level.
It will even update the count for the other user(s) properly, but not those first submitted in the original upload form.

**Closed** 2022-04-13 12:02 UTC
Labels: bug
