### ISSUE TITLE
Latest reviews?

### ISSUE THREAD

**Issue by NanakiAzakee** [rr-/TRCustoms#256] opened 2022-04-21 16:42 UTC
Hello :3
I am not sure if this is on the work yet, but I have found myself often looking for a way to see the latest reviews posted. 
The site now does allow me to see if there actually are new reviews, but in the new levels! Anything scrolling past some pages becomes almost impossible to be seen if it has gotten a review!
Thank you in advance for reading this :3

**Comment by rr-** [comment] 2022-04-21 18:46
Duplicate of #77

**Closed by rr-** 2022-04-21 18:46 UTC
